version: '3.8'

services:
  master:
    image: postgres:latest
    container_name: postgres-master
    environment:
      POSTGRES_PASSWORD: homeassistant
      POSTGRES_USER: postgres
      POSTGRES_DB: youtube-bot-filter
    ports:
      - "5434:5432"  # Expose port 5434 for the master database
    volumes:
      - /media/mgerasika/ssd13/postgres_data_master:/var/lib/postgresql/data  # Volume for PostgreSQL data (master)
      - ./master-config/postgresql.conf:/etc/postgresql/postgresql.conf  # Mount custom master config
      - ./master-config/pg_hba.conf:/etc/postgresql/pg_hba.conf  # Mount custom pg_hba.conf for master
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]  # Use custom config file
    restart: always

  slave:
    image: postgres:latest
    container_name: postgres-slave
    environment:
      POSTGRES_PASSWORD: homeassistant
      POSTGRES_USER: postgres
      POSTGRES_DB: youtube-bot-filter
    ports:
      - "5435:5432"  # Expose port 5435 for the slave database
    depends_on:
      - master  # Ensure slave starts after master
    volumes:
      - /media/mgerasika/baracuda/postgres_data:/var/lib/postgresql/data  # Volume for PostgreSQL data (slave)
      - ./slave-config/postgresql.conf:/etc/postgresql/postgresql.conf  # Mount custom slave config
      - ./slave-config/pg_hba.conf:/etc/postgresql/pg_hba.conf  # Mount custom pg_hba.conf for slave
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]  # Use custom config file for slave
    restart: always
